### ISSUE TITLE
A cleaner approach when controllers are inside a sub-folder

### ISSUE THREAD

**Issue by dotmarn** [LarrySul/laravel-api-with-passport#1]
@LarrySul In routes/api.php you can easily use the group option thereby it nullifies repetition of the folder name which houses your controllers. See code sample below:

`Route::group(['namespace' => 'Api'], function () {
    Route::post('/login', 'LoginController@login')->name('api.login');
    Route::post('/register', 'LoginController@register')->name('api.register');
});`

**Note:** The namespace is the name of your folder that houses your controllers.

**Comment by bigdevlarry** [comment]
thanks alot for the lesson implemented
